@Host = http://localhost:3000
@urlPokemon = /pokemon
@urlMovimientos = /movimientos

################
### POKEMONS ###
################

// Recuperar todos los pokemons
GET {{Host}}{{urlPokemon}}

###
// Recuperar pokemon por Id
GET {{Host}}{{urlPokemon}}/1

###
// Recuperar pokemon por nombre
GET {{Host}}{{urlPokemon}}/search/Pikachu

###
// Recuperar pokemon por Type
GET {{Host}}{{urlPokemon}}/type/Fire

###
// Registro pokemon
POST {{Host}}{{urlPokemon}}/create
Content-Type: application/json

{
    "nivel": 100, 
    "nombre": "jigglypul", 
    "tipo": "Psiquico",
    "puntosSaludActuales": 90, 
    "puntosSaludTotales": 100, 
    "puntosAtaqueBase": 30, 
    "puntosDefensaBase": 90, 
    "puntosAtaqueEspecialBase": 90,
    "puntosVelocidadBase": 90,
    "urlImage": "https://img.pokemondb.net/artwork/avif/jigglypuff.avif"
}

###
// Acualizar Pokemon
PUT {{Host}}{{urlPokemon}}/1
Content-Type: application/json

{
    "nivel": 70, 
    "nombre": "Bulbasur", 
    "tipo": "Water",
    "puntosSaludActuales": 110, 
    "puntosSaludTotales": 150, 
    "puntosAtaqueBase": 70, 
    "puntosDefensaBase": 90, 
    "puntosAtaqueEspecialBase": 120,
    "puntosVelocidadBase": 30,
    "urlImage": "https://img.pokemondb.net/artwork/avif/bulbasaur.avif"
}

###
// Borrar pokemon
DELETE {{Host}}{{urlPokemon}}/3

###################
### MOVIMIENTOS ###
###################

// Recuperar todos los movimientos
GET {{Host}}{{urlMovimientos}}

###
// Recuperar todos los movimientos
GET {{Host}}{{urlMovimientos}}/1

###
// Crear un movimiento
POST {{Host}}{{urlMovimientos}}
Content-Type: application/json

{
    "nombre": "estampida",
    "poder": 25
}


###
// Actualizar un movimiento
PUT  {{Host}}{{urlMovimientos}}/4
Content-Type: application/json

{
    "nombre": "estampida",
    "poder": 25
}

###
// Borrar movimiento
DELETE {{Host}}{{urlMovimientos}}/3