@Host = http://localhost:3000
@urlPokemon = /pokemon
@urlMovimientos = /movimientos
@urlMisPokemons = /misPokemons

################
### POKEMONS ###
################

// Recuperar todos los pokemons
GET {{Host}}{{urlPokemon}}

###
// Recuperar pokemon por Id
GET {{Host}}{{urlPokemon}}/1

###
// Recuperar pokemon por nombre
GET {{Host}}{{urlPokemon}}/search/Pikachu

###
// Recuperar pokemon por Type
GET {{Host}}{{urlPokemon}}/type/Fire

###
// Registro pokemon
POST {{Host}}{{urlPokemon}}/create
Content-Type: application/json

{
    "nivel": 100, 
    "nombre": "jugglypuff", 
    "tipo": "Hada",
    "puntosSaludActuales": 90, 
    "puntosSaludTotales": 100, 
    "puntosAtaqueBase": 30, 
    "puntosDefensaBase": 90, 
    "puntosAtaqueEspecialBase": 90,
    "puntosVelocidadBase": 90,
    "urlImage": "https://img.pokemondb.net/artwork/avif/jigglypuff.avif"
}

###
// Acualizar Pokemon
PUT {{Host}}{{urlPokemon}}/1
Content-Type: application/json

{
    "nivel": 70, 
    "nombre": "Bulbasur", 
    "tipo": "Water",
    "puntosSaludActuales": 110, 
    "puntosSaludTotales": 150, 
    "puntosAtaqueBase": 70, 
    "puntosDefensaBase": 90, 
    "puntosAtaqueEspecialBase": 120,
    "puntosVelocidadBase": 30,
    "urlImage": "https://img.pokemondb.net/artwork/avif/bulbasaur.avif"
}

###
// Borrar pokemon
DELETE {{Host}}{{urlPokemon}}/3

###################
### MOVIMIENTOS ###
###################

// Recuperar todos los movimientos
GET {{Host}}{{urlMovimientos}}

###
// Recuperar los movimientos
GET {{Host}}{{urlMovimientos}}/1

###
// Crear un movimiento
POST {{Host}}{{urlMovimientos}}
Content-Type: application/json

{
    "ataque": "Bubbles",
    "poder": 40
}


###
// Actualizar un movimiento
PUT  {{Host}}{{urlMovimientos}}/3
Content-Type: application/json

{
    "ataque": "Parachutes",
    "poder": 30
}

###
// Borrar movimiento
DELETE {{Host}}{{urlMovimientos}}/3

### 
// movimientos segun el tipo de pokemon
GET  {{Host}}{{urlMovimientos}}/type/Fuego

###
// movimientos posibles de un pokemon
GET {{Host}}{{urlMovimientos}}/possible/1

###
// Obtener una lista de pokemons que comparten el mismo movimiento
GET  {{Host}}{{urlMovimientos}}/move/1

###
// Obtener una lista de pokemons que comparten el mismo movimiento por el nombre
GET {{Host}}{{urlMovimientos}}/move/name/Bubbles


###################
### MY POKEMONS ###
###################

// Recuperar mis Pokémons con sus 4 movimientos
GET {{Host}}{{urlMisPokemons}}

###
// Recuperar mis Pokémons con sus 4 movimientos por id
GET {{Host}}{{urlMisPokemons}}/1

### 
//Crear mi Pokémon con sus movimientos
POST {{Host}}{{urlMisPokemons}}
Content-Type: application/json

{
    "apodo": "Bulba",
    "nivelActual": 3,
    "experiencia": 2,
    "estado": 1,
    "nombre": "Bulbasur"
    
}

###
// Actualizar mis pokemons
PUT {{Host}}{{urlMisPokemons}}/2
Content-Type: application/json

{
  "apodo": "PiKac",
  "nivelActual": 50,
  "experiencia": 1000,
  "estado": 1,
  "movimientos": [1, 2]
}

###
// Borrar mis pokemons
DELETE {{Host}}{{urlMisPokemons}}/1
